/*
  Please add all Javascript code to this file.
*/

//The function below will set the content on the webpage to load up articles from NYT as a default. Code snippet is taken from NYT API Console
$(window).load(function() {
  $('.loader').fadeOut('slow');
  var url = "https://api.nytimes.com/svc/topstories/v2/home.json";
  url += '?' + $.param({
      'api-key': "4bd0cad8f4814d2f98bcad03678e9603"
    });
  $.ajax({
    url: url,
    method: 'GET',
  }).done(function(result) {
    for (i = 1; i < 5; i++) { //For function will cycle through content sections on page and update them with content from NYT
      $('#title' + i).text(result.results[i].title + " - NYT");//change title, added source of news
      $('#subtitle' + i).text(result.results[i].abstract); //change subtitle
      var currentImg = (result.results[i].multimedia[0].url); //store image url
      $('#img' + i).attr("src", currentImg); //change image source to current url, this will display thumbnails next to articles
      var currentUrl = (result.results[i].url); //store article links
      $('#link' + i).html(currentUrl); //update links to articles, link url is stored to a element which is set to not display, we get access to this in the popup
      $("#impressions" + i).html(result.results[i].multimedia[0].height + " shares"); //NYT API key wasn't working, support team hasn't contacted me for using new API key so I took numerical data from top stories API to populate shares section
    }
  }).fail(function(err) {
    throw err;

  });
});
//code snippets below activate popups when one of the articles are clicked
  $('#article1').click(function () {

    $('#popUp').toggleClass('hide'); //show popup div on click
    $('h1').html($('#title1').html()); //change title in popup with the div that was clicked on
    $('p').html($('#subtitle1').html()); // change pararaph in popup with that of the div that was clicked on
    var currentUrl = ($('#link1').html());
    $('.popUpAction').attr("href", currentUrl); //change link button to guide to the url of the article that was clicked on

  });
  $('#article2').click(function () {
    $('#popUp').toggleClass('hide');
    $('h1').html($('#title2').html());
    $('p').html($('#subtitle2').html());
    var currentUrl = ($('#link2').html());
    $('.popUpAction').attr("href", currentUrl);
  });

$('#article3').click(function(){
  $('#popUp').toggleClass('hide');
  $('h1').html($('#title3').html());
  $('p').html($('#subtitle3').html());
  var currentUrl = ($('#link3').html());
  $('.popUpAction').attr("href", currentUrl);
});

$('#article4').click(function() {
  $('#popUp').toggleClass('hide');
  $('h1').html($('#title4').html());
  $('p').html($('#subtitle4').html());
  var currentUrl = ($('#link4').html());
  $('.popUpAction').attr("href", currentUrl);
});
//logic for closing popup ads
$('.closePopUp').click(function () {
  $('#popUp').toggleClass('hide');
});
//logic for toggling search function
$('#search').click(function(){
  $('#search').toggleClass('active');
});
//running NPR API on click
$('#NPR').click(function(){
//URL generated by NPR API Call Builder
 var url = "http://api.npr.org/query?fields=title,teaser,byline,text,image&requiredAssets=text,image&dateType=story&output=JSON&apiKey=MDI1ODkyNDY3MDE0NzE0MDMwMTVmMjNmYw000";


  var getJSON = function(url, callback) {
    var xhr = new XMLHttpRequest();
    xhr.open("get", url, true);
    xhr.responseType = "json";
    xhr.onload = function() {
      var status = xhr.status;
      if (status == 200) { //checks for errors
        callback(null, xhr.response);
      } else {
        callback(status);
      }
    };
    xhr.send();
  };
  //Code below takes JSON and applies it to page
  getJSON(url,
    function(err, data) {
      if (err != null) {
        alert("Something went wrong: " + err);
      } else {

        for (i = 1; i < 5; i++) {
         $('#title' + i).html(data.list.story[i].title.$text + " - NPR");// change title
          $('#subtitle' + i).html(data.list.story[i].teaser.$text); //change subtitle
         var currentImg = (data.list.story[i].image[0].src);
          //console.log(data.list.story[i].image[0].src);
         $('#img' + i).attr("src", currentImg); //change image thumbnail
          console.log(data.list.story[0].link[0].$text);
         var currentUrl = (data.list.story[i].link[0].$text);
         $('#link' + i).html(currentUrl); //change link url
       //$('#link' + i).attr("href", currentUrl);
          $("#impressions" + i).html(data.list.story[i].image[0].width + " shares"); // change share data
      }
    }})
});
//code below lets us switch back to NYT newsfeed by clicking

$("#NYT").click(function(){
  var url = "https://api.nytimes.com/svc/topstories/v2/home.json";
  url += '?' + $.param({
      'api-key': "4bd0cad8f4814d2f98bcad03678e9603"
    });
  $.ajax({
    url: url,
    method: 'GET',
  }).done(function(result) {
    for (i = 1; i < 5; i++) {
      $('#title' + i).text(result.results[i].title + " - NYT");
      $('#subtitle' + i).text(result.results[i].abstract);
      var currentImg = (result.results[i].multimedia[0].url);
      $('#img' + i).attr("src", currentImg);
      var currentUrl = (result.results[i].url);
      $('#link' + i).html(currentUrl);
      $("#impressions" + i).html(result.results[i].multimedia[0].height + " shares");
    }
  }).fail(function(err) {
    throw err;

  });
});
